defmodule Tink.Application do
  @moduledoc false

  use Application

  require Logger

  alias Tink.Config

  # Determine pool/transport config at compile time so Mix.env() is safe.
  @env Mix.env()

  @spec start(Application.start_type(), term()) :: {:ok, pid()} | {:error, term()}
  @impl true
  def start(_type, _args) do
    # Create ETS table for concurrent-safe webhook handler registry before
    # starting the supervisor so handlers can be registered immediately.
    :ets.new(:tink_webhook_handlers, [:named_table, :public, :bag])

    children = build_children()

    opts = [strategy: :one_for_one, name: Tink.Supervisor]
    Supervisor.start_link(children, opts)
  end

  defp build_children do
    [
      # HTTP connection pool (Finch)
      {Finch, name: Tink.Finch, pools: finch_pools()},

      # Rate limiter ETS backend (Hammer 7.2)
      # Backend.start_link/1 creates the named ETS table and starts the cleanup GenServer.
      rate_limiter_child_spec(),

      # Cache (if enabled)
      cache_child_spec()
    ]
    |> Enum.reject(&is_nil/1)
  end

  defp finch_pools do
    case Application.get_env(:tink, Tink.Finch) do
      nil ->
        %{
          default: [
            size: pool_size(),
            count: pool_count(),
            conn_opts: [
              timeout: timeout(),
              transport_opts: transport_opts()
            ]
          ]
        }

      custom_pools ->
        custom_pools[:pools] || %{}
    end
  end

  @default_pool_size if @env == :test, do: 2, else: 32

  defp pool_size do
    Application.get_env(:tink, :pool_size, @default_pool_size)
  end

  # Resolved at compile time — avoids Mix.env() calls at runtime in releases.
  # Dialyzer will correctly warn that non-:test branches are unreachable during test analysis;
  # this is expected and benign. The branches are live in :dev and :prod builds.
  @pool_count if @env in [:test, :dev], do: 1, else: :erlang.system_info(:logical_processors_available)

  defp pool_count, do: @pool_count

  defp timeout do
    Application.get_env(:tink, :timeout, 30_000)
  end

  # transport_opts is a runtime function rather than a module attribute because
  # :public_key.pkix_verify_hostname_match_fun/1 returns a closure, which cannot
  # be stored in a module attribute (Elixir can only escape static terms).
  # @env IS still evaluated at compile time so the dead branch is eliminated
  # by the compiler — Dialyzer will not warn about this pattern.
  if @env == :prod do
    defp transport_opts do
      [
        verify: :verify_peer,
        depth: 3,
        cacerts: :public_key.cacerts_get(),
        customize_hostname_check: [
          match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
        ],
        versions: [:"tlsv1.2", :"tlsv1.3"]
      ]
    end
  else
    defp transport_opts do
      [
        verify: :verify_peer,
        depth: 3,
        customize_hostname_check: [
          match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
        ]
      ]
    end
  end

  defp cache_child_spec do
    cache_config = Application.get_env(:tink, :cache, [])
    enabled = Keyword.get(cache_config, :enabled, true)

    if enabled do
      max_size = Keyword.get(cache_config, :max_size, 1000)
      {Cachex, name: :tink_cache, limit: max_size}
    else
      nil
    end
  end

  defp rate_limiter_child_spec do
    if Config.rate_limiting_enabled?() do
      # Read optional tuning from config, falling back to sensible defaults.
      rl_config = Application.get_env(:tink, Tink.RateLimiter.Backend, [])
      clean_period = Keyword.get(rl_config, :clean_period, :timer.minutes(5))

      # Backend.start_link/1 is generated by `use Hammer, backend: :ets, algorithm: :fix_window`.
      # It creates the named ETS table and starts a GenServer that runs periodic cleanup.
      %{
        id: Tink.RateLimiter.Backend,
        start: {Tink.RateLimiter.Backend, :start_link, [[clean_period: clean_period]]},
        restart: :permanent,
        type: :worker
      }
    else
      nil
    end
  end
end
